package com.ametis.cms.webservice;
//Generated by MyEclipse

public class ConnectorWebServiceImpl implements IConnectorWebService {
	
	public String example(String message) {
		return message;
	}
	
}