package com.ametis.cms.webservice;

import java.sql.Date;
import java.util.Collection;

import javax.jws.WebMethod;
import javax.jws.WebService;

import com.ametis.cms.datamodel.ReportRequest;
import com.ametis.cms.dto.ClaimDto;
import com.ametis.cms.dto.ClaimItemDto;
import com.ametis.cms.dto.MemberDto;
import com.ametis.cms.dto.MemberGroupDto;
//Generated by MyEclipse
@WebService (targetNamespace="http://ametis.co.id/services/ReportWebService")
public interface IReportWebService {
	
	@WebMethod
	public Collection<Object> generateReport(String keyword,
			String keyCategory, Date start, Date end, Integer status,
			Integer jenisLayanan, Integer jenisClaim) throws Exception;
	
	@WebMethod
	public ClaimDto getClaim (String claimId) throws Exception;
	
	@WebMethod
	public Integer getTotalRecord (String keyword,
	String keyCategory, Date start, Date end, Integer status,
	Integer jenisLayanan, Integer jenisClaim) throws Exception;
	
	@WebMethod
	public Collection<ClaimDto> getMemberClaimList(Integer memberId,
			Date startDate, Date endDate) ;
	
	@WebMethod
	public Collection<ClaimItemDto> getMemberClaimDetailList(Integer memberId,
				Date startDate, Date endDate) ;	
	
	@WebMethod
	public Collection<MemberDto> getParentList (String memberGroupId);
	@WebMethod
	public Collection<MemberDto> getParentListByAlphabet (String memberGroupId, String character);
	@WebMethod
	public Collection<MemberDto> getDependentList (String memberId);
	@WebMethod
	public Collection<MemberGroupDto> getMemberGroupList ();
	@WebMethod
	public Collection<ClaimDto> getListClaim (String keyword) throws Exception ;
	@WebMethod
	public ReportRequest getReportRequest (Integer id) throws Exception;


}